
// Shaders
#define IDR_VSHA_DEFAULT 101
#define IDR_FSHA_CEL     102
#define IDR_FSHA_CRT     103
#define IDR_FSHA_SOLID   104
#define IDR_FSHA_WATER   105

// Meshes
#define IDR_MESH_TEAPOT 301
#define IDR_MESH_SHIP_DSTR 302
#define IDR_MESH_SHIP_SUBM 303
#define IDR_MESH_SHIP_CRUS 304
#define IDR_MESH_SHIP_BTLE 305
#define IDR_MESH_SHIP_CARR 306
#define IDR_MESH_MARK_SHIP 307
#define IDR_MESH_MARK_FAIL 308
#define IDR_MESH_MARK_SLCT 309
#define IDR_MESH_SCRN_FRAM 310
